### ISSUE TITLE
arm64 package

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/LfMerge#136]
Please provide an arm64 build of lfmerge.

I'm specifically requesting so I don't have to emulate x86 on my Apple Silicon but understand there may also be a need down the road to run lfmerge on a Raspberry Pi 4.

**Comment by megahirt** [comment]
This sounds like a big ask to me since our production target is still x86.  I'm not an lfmerge Developer, however I would guess that an arm64 build would be out of reach since we would also need arm64 builds of all the dependencies, including fdo and liblcm.  Those are big big rocks.

**Comment by rmunn** [comment]
Agreed. This is something that sounds simple, but when you actually start trying to implement it you realize that it's an iceberg, with way more under the surface than it looks like at first glance. This might be possible at some point, but I don't think we'll be able to manage it anytime soon. Sorry.

And my comment about Raspberry Pi 4 was not actually about running lfmerge, though in context it certainly did come across that way. I was actually thinking about running other things on the Kubernetes cluster I want to set up, like a [TiddlyWiki](https://tiddlywiki.com/) server. Running lfmerge on a Raspberry Pi is not something I'm envisioning at the moment.

**Comment by longrunningprocess** [comment]
very well, I had hoped it might be something simple but sounds like that's not the case...just something to possibly keep in the back of your mind then in case the industry begins to move away from x86.  I'll go ahead and close under the assumption there's no need to keep this for "tomorrow".
