### ISSUE TITLE
Plan and implement "cache eviction" strategy for webwork dir

### ISSUE THREAD

**Issue by rmunn** [sillsdev/LfMerge#203]
The LfMerge Send/Receive process uses the `webwork` dir as, essentially, a cache: if the Mercurial repo is present, LfMerge will use it. But if it's damaged or missing, LfMerge will delete it if necessary then re-clone it from Language Depot. Thing is, the code we have right now only adds to the cache, and never evicts anything from the cache, so the `webwork` directory ends up growing without bound.

We need to decide on a cache eviction strategy for the `webwork` dir, which will probably be as simple as saying "projects that haven't done a Send/Receive in X months will have their webwork directory deleted", then defining the value of X after looking at typical usage. That way projects that are in active use will never see a slowdown, but projects that haven't been used in some time will have a slow first Send/Receive process if they are ever used again. But our data usage right now is at least 20% of *the entire space available in that storage cluster*, and in practice it's a lot more once you take snapshots and backups of the storage volume into account.

Then we need to implement that cache eviction strategy, which probably means writing a tool that will be started on a schedule (daily? weekly? monthly?) to clean up old repos from the `webwork` directory. The one tricky thing about that tool will be that it shouldn't run concurrently with an active LfMerge, since we don't want a directory disappearing during an active Send/Receive. So it should probably check for the existence of the LfMerge lockfile, and if it doesn't exist, create the lockfile before doing any destructive work like deleting repos. (It's probably safe to scan for stale repos without creating the lockfile, as long as any identified candidates are re-scanned after creating the lockfile in case LfMerge happened to update them in the meantime).

**Comment by rmunn** [comment]
To identify stale repos, we can probably use the state files and their LastStateChangeTicks property. (That's the value of the [DateTime.Ticks](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-6.0) property for that date, which represents the number of 100-nanosecond "ticks" since midnight on 0001-01-01 — yes, January 1, 1 A.D. — in the [proleptic Gregorian calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar)). It's a 64-bit int, which makes it easy to compare without converting it into a DateTime. Just create a DateTime object representing X months ago, take its Ticks property, and compare that number to the LastStateChangeTicks value in all the .state files. Then we've identified all the possibly-stale projects, and can proceed with cleaning them up.

**Comment by rmunn** [comment]
As a matter of interest, the DateTime object in C# handles dates from 1 AD at midnight of Jan 1st, to 9999 AD at 12:59:59.(lots of 9's), basically 100 nanoseconds before Jan 1st., 10000 AD. So there's no year-2038 problem to deal with.

**Comment by megahirt** [comment]
As it turns out, the webwork directory is actually not a "cache" ie. a copy of the data for performance reasons.  The webwork directory holds the only copy of images and audio on disk.  If a webwork project dir were to be deleted, the LF project would cease to be able to serve images and audio until the next S/R which would rebuild the image/audio assets folder.
