### ISSUE TITLE
Rework build branches

### ISSUE THREAD

**Issue by rmunn** [sillsdev/LfMerge#258]
We currently use three branches named `master`, `qa`, and `live`. We want to move to two branches named `develop` and `master`. The `master` branch will become `develop`, the `live` branch will become `master`, and the `qa` branch will go away entirely.

We will then start building Docker images from both the `develop` and `live` branches. The `develop` images will be tagged with a name like `2.0.115-alpha.1`, or perhaps a date and Git SHA like the Language Forge images use (`develop-$(date +%Y%m%d)-${{ github.sha }}`), and also a moving tag `develop` so that it's easy to set up a docker-compose entry to automatically use the latest `lfmerge:develop` tag.

The `fieldworks8-{master,qa,live}` branches will also be renamed at the same time.

**Comment by megahirt** [comment]
Closing as completed as in #289 and #288
