### ISSUE TITLE
Look into Chorus and FLExBridge builds needing updates

### ISSUE THREAD

**Issue by rmunn** [sillsdev/LfMerge#277]
The FLExBridge build we use in LfMerge is from the `lfmerge` branch and, well,

![This branch is 328 commits behind develop](https://user-images.githubusercontent.com/90762/173182487-e50fb772-5dab-463d-a574-5da53f7deb5e.png)

The Chorus build could also use some attention, because while https://github.com/sillsdev/chorus/pull/258 was merged into `develop`, https://github.com/sillsdev/chorus/pull/257 was never merged into `lfmerge`. So FieldWorks has benefited from the speedups (I found a 30% reduction in S/R time with that one PR alone), but LfMerge has not. I'd love to get that PR, plus any other work that has happened on `develop`, into LfMerge soon.

**Comment by josephmyers** [comment]
As part of #278, i [updated us](https://github.com/sillsdev/LfMerge/pull/278/files#diff-6e2c7ca3f50eaf036b9b47c212cfeb59f88136bcf06d761e9edede0feb0db79e) to ~[3.6.2](https://www.nuget.org/packages/SIL.ChorusPlugin.LfMergeBridge/3.4.2-beta0021) without issue. Of course, the "netcore" suffix is temporary, but maybe we can get to a point where we don't have to run off our own branch

**Comment by megahirt** [comment]
I am closing this as completed, would you agree @josephmyers ?
