### ISSUE TITLE
.NET Core build failing to find Mono.Posix.NETStandard assembly

### ISSUE THREAD

**Issue by rmunn** [sillsdev/LfMerge#279]
https://github.com/sillsdev/LfMerge/pull/278 currently builds, but when you try to run it it crashes immediately with the following exception and stacktrace:

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
>
> File name: 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at SIL.Threading.GlobalMutex.LinuxGlobalMutexAdapter.Init(Boolean initiallyOwned)
   at SIL.Threading.GlobalMutex.Initialize()
   at SIL.WritingSystems.Sldr.Initialize(Boolean offlineMode, String sldrCachePath, DateTime embeddedAllTagsTime)
   at SIL.WritingSystems.Sldr.Initialize(Boolean offlineMode, String sldrCachePath)
   at LfMerge.QueueManager.QueueManager.Main(String[] args) in /home/builder/packages/lfmerge/src/LfMergeQueueManager/QueueManager.cs:line 33

The SIL.Threading.GlobalMutex.LinuxGlobalMutexAdapter class (from GlobalMutex.cs) uses Mono.Posix.NETStandard 1.0.0 in its `netstandard2.0` build. But the [documentation for Mono.Posix](http://docs.go-mono.com/index.aspx?link=N%3AMono.Posix) now says "This namespace ... has been deprecated in favor of the new [Mono.Unix](http://docs.go-mono.com/monodoc.ashx?link=N%3aMono.Unix) namespace."

We may need to push a PR to libpalaso changing its use of Mono.Posix to use Mono.Unix instead. https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0 is from 2018, and there's a preview version that was never made public that's from 2020. But https://www.nuget.org/packages/Mono.Unix has a more recent version, from September 2021. That old Mono.Posix dependency is probably the cause of the exception above, because .NET 6 is probably not ABI-compatible with Mono.Posix.NETStandard 1.0.0.

Alternately, we may be able to implement the global-mutex code ourselves in LfMerge and no longer use SIL.Threading.GlobalMutex. That would allow us to make progress right away without needing to wait for the libpalaso PR to be reviewed and merged, if it's taking a long time.

**Comment by megahirt** [comment]
This issue was fixed in https://github.com/sillsdev/libpalaso/pull/1199
