### ISSUE TITLE
Improve LanguageForgeGetChorusNotesActionHandler return value channel

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/LfMerge#329]
right now LanguageForgeGetChorusNotesActionHandler returns a large amount of data via json serialization. By using a global static weak map we can return the data in memory instead of having to do a lot of work to pass the data back as a string.

The plan would be that there's a global static of type `ConditionalWeakTable<object, GetChorusNotesReponse>` which would use the passed in options Dictionary as the key and would create and would create the response (a new class), which would be retrieved in LfMerge `ConvertLcmToMongoComments.CallLfMergeBridge` using the same options Dictionary, we can remove the value from the global here, but this ensures that when options goes out of scope the response will get released from memory automatically.

**Comment by rmunn** [comment]
One issue is that while LfMerge can use types from LfMergeBridge, LfMergeBridge can't realistically use types from LfMerge. Which means that I'll need to move some of the type definitions (such as LfComment) out of LfMerge and into the LfMergeBridge DLL. The alternative would be to copy the data from the LfMerge types (LfComment) to the LfMergeBridge types (SerializableLfComment), but this would have many of the same drawbacks as serialization: unnecessary duplication of data.

**Comment by rmunn** [comment]
#338 has been approved and is done, but I'm holding off on merging it until the FLExBridge build process is fixed and producing NuGet packages again. Right now there's no NuGet package containing the corresponding FLExBridge code, so merging #338 in its current state would require changing the LfMerge build process to include checking out the FLExBridge Git repo as a submodule. I'd rather just consume the NuGet package, which means letting this PR sit for a while until the FLExBridge build is fixed.

**Comment by rmunn** [comment]
FLExBridge build process is fixed, so #338 now relies on NuGet packages. It's already been approved and I just got the tests running, so I'm about to merge it.
